[project]
name = "market-pulse"
version = "0.1.0"
description = "Market Pulse Radar app"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = [
    "black",
    "mypy",
    "pre-commit",
    "pytest",
    "ruff",
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.11"
strict = true
